/**
 * Scans public/images/background/promo/landing for .webp files and emits
 * src/generated/landingImageManifest.ts.
 *
 * The resolver in src/utils/promo/landing-image-resolver.ts consults this
 * manifest so it can swap light↔dark when the requested asset isn't on disk.
 *
 * Run: npx tsx scripts/build-landing-image-manifest.ts
 */

import fs from "node:fs/promises";
import path from "node:path";

const LANDING_ROOT = path.join(process.cwd(), "public", "images", "background", "promo", "landing");
const URL_BASE = "/images/background/promo/landing";
const OUT = path.join(process.cwd(), "src", "generated", "landingImageManifest.ts");

async function collectWebpFiles(absDir: string, relDir: string): Promise<string[]> {
  const entries = await fs.readdir(absDir, { withFileTypes: true });
  const out: string[] = [];
  for (const e of entries) {
    const full = path.join(absDir, e.name);
    const rel = relDir ? `${relDir}/${e.name}` : e.name;
    if (e.isDirectory()) {
      out.push(...(await collectWebpFiles(full, rel)));
    } else if (e.isFile() && e.name.toLowerCase().endsWith(".webp")) {
      out.push(rel.replace(/\\/g, "/"));
    }
  }
  return out;
}

async function main() {
  const rels = (await collectWebpFiles(LANDING_ROOT, "")).sort();
  const urls = rels.map((r) => `${URL_BASE}/${r}`);
  const body = urls.map((u) => `  ${JSON.stringify(u)},`).join("\n");
  const file = `// AUTO-GENERATED by scripts/build-landing-image-manifest.ts — do not edit by hand.
// Regenerate: npm run build:landing-manifest

export const LANDING_IMAGE_MANIFEST = new Set<string>([
${body}
]);
`;
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, file, "utf8");
  console.log(`Wrote ${urls.length} entries to ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
