/**
 * Scans public/videos/landing for clip files and emits
 * src/generated/landingVideoManifest.ts.
 *
 * The video twin of `build-landing-image-manifest.ts`. It exists because draw 9 gave the
 * hero clips a light/dark dimension AND a real gap (GearWrench × Ryobi was never produced).
 * Without a manifest the resolver would list `<source>`s for clips that don't exist and rely
 * on the browser advancing past each 404 — which works, but emits console errors on every
 * load of an affected page and trips the e2e watchdog. The manifest lets
 * `getLandingHeroVideoPaths` list only clips that are actually on disk.
 *
 * Run: npx tsx scripts/build-landing-video-manifest.ts
 */

import fs from "node:fs/promises";
import path from "node:path";

const VIDEO_ROOT = path.join(process.cwd(), "public", "videos", "landing");
const URL_BASE = "/videos/landing";
const OUT = path.join(process.cwd(), "src", "generated", "landingVideoManifest.ts");

async function collectClips(absDir: string, relDir: string): Promise<string[]> {
  const entries = await fs.readdir(absDir, { withFileTypes: true });
  const out: string[] = [];
  for (const e of entries) {
    const full = path.join(absDir, e.name);
    const rel = relDir ? `${relDir}/${e.name}` : e.name;
    if (e.isDirectory()) {
      out.push(...(await collectClips(full, rel)));
    } else if (e.isFile() && /\.(webm|mp4)$/i.test(e.name)) {
      out.push(rel.replace(/\\/g, "/"));
    }
  }
  return out;
}

async function main() {
  const rels = (await collectClips(VIDEO_ROOT, "")).sort();
  const urls = rels.map((r) => `${URL_BASE}/${r}`);
  const body = urls.map((u) => `  ${JSON.stringify(u)},`).join("\n");
  const file = `// AUTO-GENERATED by scripts/build-landing-video-manifest.ts — do not edit by hand.
// Regenerate: npm run build:landing-video-manifest

export const LANDING_VIDEO_MANIFEST = new Set<string>([
${body}
]);
`;
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, file, "utf8");
  console.log(`Wrote ${urls.length} entries to ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
