/**
 * Scans public/images/upsells for .webp files and emits src/generated/upsellImageManifest.ts
 * Run: npx tsx scripts/build-upsell-image-manifest.ts
 */

import fs from "node:fs/promises";
import path from "node:path";

const UPS_ROOT = path.join(process.cwd(), "public", "images", "upsells");
const OUT = path.join(process.cwd(), "src", "generated", "upsellImageManifest.ts");

async function collectWebpFiles(absDir: string, relDir: string): Promise<string[]> {
  const entries = await fs.readdir(absDir, { withFileTypes: true });
  const out: string[] = [];
  for (const e of entries) {
    const full = path.join(absDir, e.name);
    const rel = relDir ? `${relDir}/${e.name}` : e.name;
    if (e.isDirectory()) {
      out.push(...(await collectWebpFiles(full, rel)));
    } else if (e.isFile() && e.name.toLowerCase().endsWith(".webp")) {
      out.push(rel.replace(/\\/g, "/"));
    }
  }
  return out;
}

async function main() {
  const keys = (await collectWebpFiles(UPS_ROOT, "")).sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)},`).join("\n");
  const file = `// AUTO-GENERATED by scripts/build-upsell-image-manifest.ts — do not edit by hand.
// Regenerate: npm run build:upsell-manifest

export const UPSELL_IMAGE_MANIFEST = new Set<string>([
${body}
]);
`;
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, file, "utf8");
  console.log(`Wrote ${keys.length} entries to ${path.relative(process.cwd(), OUT)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
